export { default as ProductCard } from './components/ProductCard';
export { default as ProductList } from './components/ProductList';
export { default as FilterSidebar } from './components/FilterSidebar';
export { default as ProductDetails } from './components/ProductDetails';
export { default as SearchResults } from './components/SearchResults';
export { default as SortSelector } from './components/SortSelector';
export { default as ArtistCard } from './components/ArtistCard';
export { default as ArtistFilters } from './components/ArtistFilters';
export * from './hooks/useProductFilters';
export * from './hooks/useProducts';
export * from './hooks/useArtists';
export { getArtists, type Artist } from './services/artistService';
export { getProducts, getProductById } from './services/productService';
